-- VAU seed data — Israeli experience-gift marketplace (Hebrew default, Russian second)

INSERT INTO categories (name_he, name_ru, name_en, slug, emoji, img, tint) VALUES
('אקסטרים', 'Экстрим', 'Extreme', 'extreme', '🪂', 'https://images.unsplash.com/photo-1521673461164-de300ebcfb17?auto=format&fit=crop&w=900&q=80', 'from-coral-500 to-coral-700'),
('טיסות ושמיים', 'Полёты', 'Flights', 'flights', '🎈', 'https://images.unsplash.com/photo-1507608443039-bfde4fbcd142?auto=format&fit=crop&w=900&q=80', 'from-teal-400 to-teal-600'),
('ספא ויופי', 'Спа и красота', 'Spa & Beauty', 'spa', '🧖', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=900&q=80', 'from-berry-500 to-coral-400'),
('קולינריה', 'Гастрономия', 'Gastronomy', 'gastro', '🍷', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=80', 'from-sun-500 to-coral-600'),
('רומנטיקה', 'Романтика', 'Romance', 'romance', '💕', 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?auto=format&fit=crop&w=900&q=80', 'from-coral-400 to-berry-500'),
('סדנאות', 'Мастер-классы', 'Workshops', 'workshops', '🎨', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=900&q=80', 'from-teal-500 to-berry-600');

INSERT INTO experiences (title_he, title_ru, title_en, description_he, description_ru, description_en, price, old_price, rating, reviews_count, duration_he, duration_ru, participants_he, participants_ru, emoji, img, tint, category_id, is_best_seller) VALUES
('צניחה חופשית מעל החוף', 'Прыжок с парашютом над побережьем', 'Skydiving over the coast', 'קפיצת טנדם מגובה 4,000 מטר עם נחיתה רכה מול הים.', 'Тандемный прыжок с высоты 4000 м с мягкой посадкой у моря.', 'Tandem jump from 4,000m with a soft landing by the sea.', 1290, 1490, 4.9, 850, 'כ־3 שעות', 'около 3 часов', 'יחיד', '1 человек', '🪂', 'https://images.unsplash.com/photo-1521673461164-de300ebcfb17?auto=format&fit=crop&w=1000&q=80', 'from-coral-500 to-coral-700', (SELECT id FROM categories WHERE slug='extreme'), TRUE),
('טיסת בלון פורח בזריחה', 'Полёт на воздушном шаре на рассвете', 'Sunrise hot air balloon flight', 'המראה שקטה מעל עמק יזרעאל בשעת הזריחה, כולל טקס שמפניה.', 'Тихий подъём над Изреельской долиной на рассвете и тост шампанским.', 'A quiet sunrise ascent over the Jezreel Valley with a champagne toast.', 890, NULL, 5.0, 420, 'כ־4 שעות', 'около 4 часов', 'לזוג', 'для двоих', '🎈', 'https://images.unsplash.com/photo-1507608443039-bfde4fbcd142?auto=format&fit=crop&w=1000&q=80', 'from-teal-400 to-teal-600', (SELECT id FROM categories WHERE slug='flights'), TRUE),
('יום פינוק זוגי בספא יוקרה', 'День роскошного спа для двоих', 'Luxury spa day for two', 'עיסוי זוגי, גישה חופשית לבריכות מים חמים, סאונות ופינת כיבוד.', 'Парный массаж, тёплые бассейны, сауны и зона отдыха.', 'Couples massage, warm pools, saunas and a refreshment lounge.', 690, 850, 4.8, 1240, 'יום שלם', 'целый день', 'לזוג', 'для двоих', '🧖', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1000&q=80', 'from-berry-500 to-coral-400', (SELECT id FROM categories WHERE slug='spa'), TRUE),
('טעימות יין ביקב בוטיק', 'Дегустация вин на бутиковой винодельне', 'Boutique winery tasting', 'סיור מודרך בין הגפנים, טעימת יינות פרימיום ולוח גבינות מקומי.', 'Экскурсия по виноградникам, дегустация премиальных вин и сырная тарелка.', 'Guided vineyard tour, premium wine tasting and a local cheese board.', 420, NULL, 4.7, 560, 'כשעתיים', 'около 2 часов', 'לזוג', 'для двоих', '🍷', 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80', 'from-sun-500 to-coral-600', (SELECT id FROM categories WHERE slug='gastro'), FALSE),
('נהיגת ספורט על מסלול מרוצים', 'Гонка на спорткаре по трассе', 'Sports car track experience', 'נהיגה עצמאית ברכב ספורט על מסלול מקצועי, עם תדריך נהג מרוצים.', 'Самостоятельное вождение спорткара на трассе с инструктажем гонщика.', 'Self-drive a sports car on a pro track with a racing-driver briefing.', 950, 1100, 4.8, 320, 'כשעתיים', 'около 2 часов', 'יחיד', '1 человек', '🏎️', 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1000&q=80', 'from-coral-500 to-coral-700', (SELECT id FROM categories WHERE slug='extreme'), FALSE),
('ארוחת שף פרטית בבית', 'Ужин с личным шефом дома', 'Private chef dinner at home', 'שף פרטי מגיע אליכם הביתה עם תפריט טעימות אישי ויין תואם.', 'Личный шеф приезжает к вам с дегустационным меню и вином.', 'A private chef comes to your home with a tasting menu and paired wine.', 1490, NULL, 4.9, 190, 'כ־3 שעות', 'около 3 часов', 'עד 6 סועדים', 'до 6 гостей', '👨‍🍳', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=80', 'from-sun-500 to-coral-600', (SELECT id FROM categories WHERE slug='gastro'), FALSE),
('שיט קייקים בנהר הירדן', 'Сплав на каяках по Иордану', 'Kayaking on the Jordan River', 'מסלול מים זורמים בין נופי הצפון, מתאים למשפחות ולחובבי אקשן.', 'Маршрут по бурной воде среди северных пейзажей — для семей и любителей экшена.', 'A flowing-water route through northern scenery for families and thrill-seekers.', 260, NULL, 4.6, 730, 'כשעתיים', 'около 2 часов', 'לזוג', 'для двоих', '🛶', 'https://images.unsplash.com/photo-1545579133-99bb5ab189bd?auto=format&fit=crop&w=1000&q=80', 'from-coral-500 to-coral-700', (SELECT id FROM categories WHERE slug='extreme'), FALSE),
('סדנת קדרות על אובניים', 'Мастер-класс гончарного дела', 'Pottery wheel workshop', 'יוצרים כלי חרס על האובניים בהדרכת אמן, וחוזרים הביתה עם היצירה.', 'Создаёте керамику на гончарном круге с мастером и забираете работу домой.', 'Throw your own ceramics on the wheel with an artist and take your piece home.', 320, 380, 4.9, 480, 'כשעתיים וחצי', 'около 2,5 часов', 'יחיד', '1 человек', '🎨', 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=1000&q=80', 'from-teal-500 to-berry-600', (SELECT id FROM categories WHERE slug='workshops'), FALSE),
('מצנח רחיפה מעל הכרמל', 'Параглайдинг над Кармелем', 'Paragliding over Carmel', 'טיסת טנדם עם מדריך מוסמך מעל מצוקי הכרמל והנוף לים.', 'Тандемный полёт с инструктором над скалами Кармеля и видом на море.', 'A tandem flight with a certified guide over the Carmel cliffs and sea view.', 540, NULL, 4.8, 300, 'כשעה וחצי', 'около 1,5 часов', 'יחיד', '1 человек', '🪂', 'https://images.unsplash.com/photo-1600250395178-40fe752e5189?auto=format&fit=crop&w=1000&q=80', 'from-teal-400 to-teal-600', (SELECT id FROM categories WHERE slug='flights'), FALSE),
('סדנת סושי עם שף יפני', 'Мастер-класс суши с японским шефом', 'Sushi workshop with a Japanese chef', 'לומדים לגלגל מייקי וניגירי כמו מקצוענים, ואוכלים עם סאקה.', 'Учитесь крутить маки и нигири как профи и едите с саке.', 'Learn to roll maki and nigiri like a pro, then eat your creations with sake.', 390, NULL, 4.9, 410, 'כשעתיים', 'около 2 часов', 'לזוג', 'для двоих', '🍣', 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1000&q=80', 'from-teal-500 to-berry-600', (SELECT id FROM categories WHERE slug='workshops'), FALSE),
('רכיבת סוסים בשקיעה', 'Конная прогулка на закате', 'Sunset horseback ride', 'טיול רכיבה זוגי לאורך שביל טבע בשעת השקיעה, בליווי מדריך.', 'Парная верховая прогулка по природной тропе на закате с инструктором.', 'A couples ride along a nature trail at sunset with a guide.', 480, 560, 4.7, 220, 'כשעתיים', 'около 2 часов', 'לזוג', 'для двоих', '🐎', 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=1000&q=80', 'from-coral-400 to-berry-500', (SELECT id FROM categories WHERE slug='romance'), FALSE),
('שיט יאכטה פרטית בשקיעה', 'Частная яхта на закате', 'Private sunset yacht cruise', 'הפלגה זוגית ביאכטה יוקרתית מול חופי תל אביב, עם שמפניה ופינוקים.', 'Парная прогулка на роскошной яхте вдоль Тель-Авива с шампанским.', 'A couples cruise on a luxury yacht along the Tel Aviv shoreline with champagne.', 1150, NULL, 5.0, 160, 'כשעתיים', 'около 2 часов', 'לזוג', 'для двоих', '🛥️', 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1000&q=80', 'from-coral-400 to-berry-500', (SELECT id FROM categories WHERE slug='romance'), TRUE);

-- ── Businesses / partners (one per category theme) ──
INSERT INTO businesses (slug, name_he, name_ru, description_he, description_ru, location_he, location_ru, emoji, since, rating) VALUES
('partner-extreme', 'אדרנלין ישראל', 'Адреналин Израиль', 'חברת אקסטרים מובילה עם מדריכים מוסמכים וציוד בטיחות מהשורה הראשונה, פועלת מ־2011.', 'Ведущая компания экстрим-впечатлений: сертифицированные инструкторы и снаряжение высшего класса с 2011 года.', 'מרכז, צפון ודרום', 'Центр, север и юг', '🪂', 2011, 4.9),
('partner-flights', 'שמיים פתוחים', 'Открытое небо', 'טיסות בלון, מצנחי רחיפה וחוויות אוויר, בהובלת טייסים ותיקים ובכפוף לרשות התעופה.', 'Полёты на шарах, параглайдинг и воздушные впечатления с опытными пилотами и допуском авиационных властей.', 'עמק יזרעאל והכרמל', 'Изреельская долина и Кармель', '🎈', 2014, 5.0),
('partner-spa', 'נווה שלווה', 'Оазис спокойствия', 'רשת ספא בוטיק עם מטפלים מקצועיים, מרחבי מים חמים וטיפולים אישיים.', 'Сеть бутик-спа с профессиональными терапевтами, тёплыми бассейнами и индивидуальными процедурами.', 'תל אביב, הרצליה, ים המלח', 'Тель-Авив, Герцлия, Мёртвое море', '🧖', 2009, 4.8),
('partner-gastro', 'טעמים', 'Вкусы', 'שפים פרטיים, יקבי בוטיק וחוויות קולינריות, בשיתוף יצרנים מקומיים.', 'Частные шефы, бутиковые винодельни и кулинарные впечатления в партнёрстве с местными производителями.', 'הגליל, השרון ותל אביב', 'Галилея, Шарон и Тель-Авив', '🍷', 2015, 4.8),
('partner-romance', 'רגעים', 'Моменты', 'חוויות זוגיות ורומנטיות: הפלגות, רכיבה ושקיעות בלתי נשכחות.', 'Романтические впечатления для пар: круизы, верховая езда и незабываемые закаты.', 'חוף תל אביב והצפון', 'Побережье Тель-Авива и север', '💕', 2016, 4.9),
('partner-workshops', 'יוצרים', 'Мастера', 'סטודיו לסדנאות יצירה עם אמנים ושפים — קדרות, סושי, אמנות ועוד.', 'Студия творческих мастер-классов с художниками и шефами — гончарство, суши, искусство и не только.', 'תל אביב ויפו', 'Тель-Авив и Яффо', '🎨', 2018, 4.9);

-- Link each experience to its category's partner business.
UPDATE experiences e SET business_id = b.id
FROM categories c, businesses b
WHERE e.category_id = c.id AND b.slug = 'partner-' || c.slug;
